CREATE DATABASE KR;
USE KR;

CREATE TABLE BOOKS (
  BOOK_ID  INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME     VARCHAR(30) NOT NULL,
  ISBN     VARCHAR(12),
  GENRE    VARCHAR(30) NOT NULL,
  YEAR     INT(4)      NOT NULL,
  QUANTITY INT(3)      NOT NULL
);


CREATE TABLE AUTHORS (
  AUTHOR_ID   INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SURNAME     VARCHAR(30) NOT NULL,
  NAME        VARCHAR(30) NOT NULL,
  SECOND_NAME VARCHAR(30),
  BIRTHDAY    DATE        NOT NULL,
  COUNTRY     VARCHAR(30) NOT NULL
);


CREATE TABLE BOOKS_AUTHORS (
  AUTHOR_ID INT NOT NULL,
  BOOK_ID   INT NOT NULL
);

ALTER TABLE BOOKS_AUTHORS
  ADD CONSTRAINT PRIMARY KEY (AUTHOR_ID, BOOK_ID);

ALTER TABLE BOOKS_AUTHORS
  ADD CONSTRAINT FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (AUTHOR_ID);
ALTER TABLE BOOKS_AUTHORS
  ADD CONSTRAINT FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID);


CREATE TABLE LIBRARIANS (
  LIBRARIAN_ID INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SURNAME      VARCHAR(30) NOT NULL,
  NAME         VARCHAR(30) NOT NULL,
  SECOND_NAME  VARCHAR(30) NOT NULL,
  PASSWORD     VARCHAR(30) NOT NULL,
  EMAIL        VARCHAR(30) NOT NULL
);


CREATE TABLE READERS (
  READER_ID   INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SURNAME     VARCHAR(30) NOT NULL,
  NAME        VARCHAR(30) NOT NULL,
  SECOND_NAME VARCHAR(30) NOT NULL,
  PASSWORD    VARCHAR(30) NOT NULL,
  EMAIL       VARCHAR(30) NOT NULL,
  BIRTHDAY    DATE,
  GENDER      VARCHAR(30) NOT NULL
);

CREATE TABLE FORMS (
  FORM_ID       INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BOOK_ID       INT  NOT NULL,
  READER_ID     INT  NOT NULL,
  LIBRARIAN_ID  INT  NOT NULL,
  RECEIVAL_TYPE CHAR(10),
  RECEIVAL_DATE DATE NOT NULL,
  RETURN_DATE   DATE NOT NULL
);

ALTER TABLE FORMS
  ADD CONSTRAINT FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID);
ALTER TABLE FORMS
  ADD CONSTRAINT FOREIGN KEY (LIBRARIAN_ID) REFERENCES LIBRARIANS (LIBRARIAN_ID);
ALTER TABLE FORMS
  ADD CONSTRAINT FOREIGN KEY (READER_ID) REFERENCES READERS (READER_ID);
